#!/usr/bin/env python3
import subprocess

objective = input("Indique la ip objetivo \n")

scan = (['nmap', '-Pn', '-sC', '-sV', '-p-', objective, '--min-rate', "5000",'-v'])

output_file = ([ '-oN', 'Wnscan-Out'])

file_bool = False

while True:
    file_output = input("¿Desea almacenar los resultados en un archivo? (Y/N) \n")

    if file_output.casefold()=='y':
        file_bool=True
        break
    elif file_output.casefold()=='n':
        file_bool=False
        break


    else: print('Opcion no valida \n')  

if file_bool==True:
    scan.extend(output_file)
    subprocess.call(scan)

    print('\n ---»Se creo un archivo con el nombre Wnscan-Out')

else: subprocess.call(scan)

